global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: plataforma-apis
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'bff-api:5000'
          - 'auth-api:5001'
          - 'conteudo-api:5002'
          - 'alunos-api:5003'
          - 'pagamentos-api:5004'
